VENUE_TYPES = [
	("J", "Journal Article"),
	("B", "Whole Book"),
	("C", "Book Chapter"),
	("P", "Conference Proceedings"),
	("M", "Master Thesis"),
	("D", "Doctorate Thesis"),
	("R", "Report"),
	("G", "Magazine"),
	("X", "Miscellaneous"),
	("A", "Archives"),
]

ARTICLE_TYPES = {
	"article": "J",
	"Early Access Articles": "J",
	"book": "B",
	"Book": "B",
	"Book Series": "B",
	"booklet": "X",
	"conference": "P",
	"Conferences": "P",
	"conference-proceeding": "P",
	"Conference Proceeding": "P",
	"proceedings-article": "P",
	"inbook": "X",
	"incollection": "X",
	"inproceedings": "P",
	"Journal-article": "J",
	"journal-article": "J",
	"Journal": "J",
	"Journals": "J",
	"manual": "X",
	"masterthesis": "M",
	"misc": "X",
	"phdthesis": "D",
	"proceedings": "X",
	"techreport": "R",
	"unpublished": "A",
	"other": "X",
	"Magazines": "G",
}

FULL_TEXT_TYPES = [
	("A", "text/plain"),
	("B", "video/webm"),
	("C", "text/css"),
	("D", "audio/wav"),
	("E", "audio/mpeg"),
	("I", "audio/aac"),
	("J", "image/jpeg"),
	("H", "text/html"),
	("G", "image/gif"),
	("L", "text/xml"),
	("O", "audio/ogg"),
	("N", "image/png"),
	("M", "application/msword"),
	("P", "application/pdf"),
	("Q", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"),
	("R", "application/javascript"),
	("S", "image/svg"),
	("T", "application/x-tar"),
	("U", "application/octet-stream"),
	("V", "text/csv"),
	("W", "image/webp"),
	("Y", "video/ogg"),
	("X", "application/xml"),
	("Z", "application/zip"),

	("0", "application/json"),
	("1", "application/vnd.ms-excel"),
	("2", "application/vnd.ms-powerpoint"),
	("3", "application/vnd.openxmlformats-officedocument.wordprocessingml.document"),
	("4", "video/mp4"),
	("5", "application/vnd.openxmlformats-officedocument.presentationml.presentation"),
	("7", "application/x-7z-compressed"),
	("6", "multipart/mixed"),
	("8", "multipart/alternative"),
	("9", "multipart/related")]

FULL_TEXT_TYPES_REVERSE = {k: v for v, k in FULL_TEXT_TYPES}

FULL_TEXT_STATUS = [
	("E", "Empty"),
	("N", "Not found"),
	("D", "Downloaded"),
	("U", "Uploaded")
]
