# Generated by Django 4.2.1 on 2023-06-29 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('query', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='query',
            name='publication_list',
        ),
        migrations.CreateModel(
            name='QueryPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=2048)),
                ('source', models.CharField(max_length=1024)),
                ('headers', models.TextField()),
                ('format', models.CharField(max_length=2048)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
