# Generated by Django 4.2.1 on 2023-06-29 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0002_remove_query_publication_list_queryplatform'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='platform',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='query.queryplatform'),
        ),
    ]
