# Generated by Django 4.2.1 on 2023-06-29 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0003_query_platform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queryplatform',
            name='format',
        ),
    ]
