# Generated by Django 4.2.1 on 2023-06-29 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0004_remove_queryplatform_format'),
    ]

    operations = [
        migrations.RenameField(
            model_name='queryplatform',
            old_name='headers',
            new_name='params',
        ),
    ]
