# Generated by Django 4.2.1 on 2023-06-29 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0005_rename_headers_queryplatform_params'),
    ]

    operations = [
        migrations.AddField(
            model_name='queryplatform',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
