# Generated by Django 4.2.1 on 2023-06-29 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0006_queryplatform_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='queryplatform',
            name='help_link',
            field=models.URLField(null=True),
        ),
    ]
