# Generated by Django 4.2.1 on 2023-06-30 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('publication', '0002_alter_event_name_alter_event_publisher_and_more'),
        ('query', '0007_queryplatform_help_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='query',
            old_name='text',
            new_name='query',
        ),
        migrations.AddField(
            model_name='query',
            name='found_publications',
            field=models.ManyToManyField(to='publication.publication'),
        ),
        migrations.AddField(
            model_name='query',
            name='results',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='query',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
