# Generated by Django 5.0.4 on 2024-04-08 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('type', models.CharField(choices=[('J', 'Journal Article'), ('B', 'Whole Book'), ('C', 'Book Chapter'), ('P', 'Conference Proceedings'), ('M', 'Master Thesis'), ('D', 'Doctorate Thesis'), ('R', 'Report'), ('G', 'Magazine'), ('X', 'Miscellaneous'), ('A', 'Archives')], max_length=1)),
                ('publisher', models.CharField(blank=True, max_length=256)),
                ('volume', models.CharField(max_length=128)),
                ('issue', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=256)),
                ('last_name', models.CharField(max_length=256)),
                ('ORCID', models.SlugField(max_length=1024, null=True)),
                ('affiliation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='publication.affiliation')),
            ],
        ),
        migrations.AddField(
            model_name='affiliation',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='publication.country'),
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doi', models.SlugField(max_length=256, unique=True)),
                ('title', models.CharField(max_length=1024, unique=True)),
                ('year', models.PositiveSmallIntegerField()),
                ('datetime_added', models.DateTimeField(auto_now=True)),
                ('abstract', models.TextField(blank=True)),
                ('authors', models.ManyToManyField(to='publication.author')),
                ('keywords', models.ManyToManyField(to='publication.keywords')),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='publication.source')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='publication.venue')),
            ],
        ),
        migrations.CreateModel(
            name='FullText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('H', 'text/html'), ('P', 'application/pdf'), ('X', 'text/xml'), ('T', 'text/plain')], default='T', max_length=1)),
                ('status', models.CharField(choices=[('E', 'Empty'), ('N', 'Not found'), ('D', 'Downloaded'), ('U', 'Uploaded')], default='E', max_length=1)),
                ('file', models.FileField(blank=True, upload_to='full_text')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publication.publication')),
            ],
        ),
    ]
