# Generated by Django 5.0.4 on 2024-04-17 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0002_alter_affiliation_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='affiliation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authors', to='publication.affiliation'),
        ),
        migrations.AlterField(
            model_name='fulltext',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='full_texts', to='publication.publication'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publications', to='publication.source'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='papers', to='publication.venue'),
        ),
    ]
