# Generated by Django 5.0.4 on 2024-04-17 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0003_alter_author_affiliation_alter_fulltext_publication_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Keywords',
            new_name='Keyword',
        ),
    ]
