# Generated by Django 5.0.4 on 2024-04-17 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0005_affiliation_first_created_affiliation_last_update_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='affiliation',
            name='first_created',
        ),
        migrations.RemoveField(
            model_name='affiliation',
            name='last_update',
        ),
        migrations.RemoveField(
            model_name='author',
            name='first_created',
        ),
        migrations.RemoveField(
            model_name='author',
            name='last_update',
        ),
        migrations.RemoveField(
            model_name='country',
            name='first_created',
        ),
        migrations.RemoveField(
            model_name='country',
            name='last_update',
        ),
        migrations.RemoveField(
            model_name='keyword',
            name='first_created',
        ),
        migrations.RemoveField(
            model_name='keyword',
            name='last_update',
        ),
        migrations.RemoveField(
            model_name='source',
            name='first_created',
        ),
        migrations.RemoveField(
            model_name='source',
            name='last_update',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='first_created',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='last_update',
        ),
    ]
