# Generated by Django 5.0.4 on 2024-04-28 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0009_alter_publication_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='fulltext',
            name='url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='fulltext',
            name='file',
            field=models.FileField(blank=True, upload_to='storage/full_texts'),
        ),
    ]
