# Generated by Django 5.0.4 on 2024-04-28 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0010_fulltext_url_alter_fulltext_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fulltext',
            name='url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
