# Generated by Django 4.2.6 on 2023-10-18 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0001_initial'),
        ('mapping', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('type', models.CharField(choices=[('T', 'Text'), ('N', 'Number'), ('B', 'Boolean'), ('L', 'List'), ('S', 'Select One'), ('O', 'Multi-Select'), ('C', 'Coding')], max_length=1)),
                ('publication_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapping.publicationlist')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publication.publication')),
                ('review_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapping.reviewfield')),
            ],
        ),
        migrations.RemoveField(
            model_name='userfield',
            name='publication_list',
        ),
        migrations.RemoveField(
            model_name='userfield',
            name='reviewer',
        ),
        migrations.RemoveField(
            model_name='userfieldreview',
            name='publication',
        ),
        migrations.RemoveField(
            model_name='userfieldreview',
            name='review',
        ),
        migrations.RemoveField(
            model_name='userfieldreview',
            name='reviewer_field',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='review',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='UserField',
        ),
        migrations.DeleteModel(
            name='UserFieldReview',
        ),
    ]
