# Generated by Django 4.2.1 on 2023-07-03 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0002_rename_followers_publicationlist_subscriptions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicationlist',
            old_name='subscriptions',
            new_name='followers',
        ),
    ]
