# Generated by Django 4.2.1 on 2023-07-03 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0003_rename_subscriptions_publicationlist_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationlist',
            name='subscribers',
            field=models.ManyToManyField(related_name='my_subscriptions', to='mapping.publicationlist'),
        ),
        migrations.AlterField(
            model_name='publicationlist',
            name='followers',
            field=models.ManyToManyField(related_name='my_followers', to='mapping.publicationlist'),
        ),
    ]
