# Generated by Django 4.2.1 on 2023-07-03 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0004_publicationlist_subscribers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicationlist',
            old_name='subscribers',
            new_name='subscriptions',
        ),
    ]
