# Generated by Django 4.2.6 on 2023-10-24 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0001_initial'),
        ('mapping', '0005_alter_reviewfieldvaluetext_publication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewfieldvaluetext',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publication.publication'),
        ),
    ]
