# Generated by Django 4.2.1 on 2023-06-07 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_review_description_review_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='publication_lists',
        ),
        migrations.AddField(
            model_name='publicationlist',
            name='review',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='review.review'),
            preserve_default=False,
        ),
    ]
