# Generated by Django 4.2.1 on 2023-06-07 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_remove_review_publication_lists_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='secret_key',
            field=models.SlugField(max_length=255),
        ),
    ]
