# Generated by Django 4.2.1 on 2023-06-09 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0005_userpreferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='default_page_size',
            field=models.PositiveSmallIntegerField(default=25),
        ),
    ]
