# Generated by Django 4.2.1 on 2023-06-09 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0006_userpreferences_default_page_size'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Journal',
        ),
    ]
