# Generated by Django 4.2.6 on 2023-11-06 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('publication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fulltext',
            name='status',
            field=models.CharField(choices=[('E', 'EMPTY'), ('A', 'AVAILABLE'), ('D', 'DOWNLOADED'), ('U', 'UPLOADED')], default='E', max_length=1),
        ),
        migrations.AddField(
            model_name='fulltext',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fulltext',
            name='address',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='fulltext',
            name='url',
            field=models.URLField(blank=True, max_length=1024),
        ),
    ]
