# Generated by Django 4.2.1 on 2023-06-29 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=2048),
        ),
        migrations.AlterField(
            model_name='event',
            name='publisher',
            field=models.CharField(blank=True, max_length=2048),
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(max_length=2048),
        ),
    ]
