# Generated by Django 4.2.6 on 2023-11-06 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('publication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fulltext',
            name='url',
            field=models.URLField(blank=True, max_length=1024),
        ),
    ]
