# Generated by Django 4.2.6 on 2023-11-06 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0007_remove_reviewfield_publication_list_and_more'),
        ('publication', '0002_fulltext_status_fulltext_user_alter_fulltext_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FullTextAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, upload_to='full_text')),
                ('status', models.CharField(choices=[('E', 'Empty'), ('A', 'Available'), ('D', 'Downloaded'), ('U', 'Uploaded')], default='E', max_length=1)),
                ('full_text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publication.fulltext')),
                ('mapping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapping.mapping')),
            ],
        ),
    ]
