# Generated by Django 4.2.6 on 2024-05-06 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0007_remove_reviewfield_publication_list_and_more'),
        ('publication', '0004_alter_fulltextaccess_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Keywords',
            new_name='Keyword',
        ),
        migrations.AlterField(
            model_name='affiliation',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliations', to='publication.country'),
        ),
        migrations.AlterField(
            model_name='author',
            name='affiliation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='publication.affiliation'),
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('J', 'Journal Article'), ('B', 'Whole Book'), ('C', 'Book Chapter'), ('P', 'Conference Proceedings'), ('M', 'Master Thesis'), ('D', 'Doctorate Thesis'), ('R', 'Report'), ('G', 'Magazine'), ('X', 'Miscellaneous'), ('A', 'Archives')], max_length=1),
        ),
        migrations.AlterField(
            model_name='fulltext',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='full_text', to='publication.publication'),
        ),
        migrations.AlterField(
            model_name='fulltextaccess',
            name='full_text',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesses', to='publication.fulltext'),
        ),
        migrations.AlterField(
            model_name='fulltextaccess',
            name='mapping',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='full_text_accesses', to='mapping.mapping'),
        ),
        migrations.AlterField(
            model_name='fulltextaccess',
            name='status',
            field=models.CharField(choices=[('E', 'Empty'), ('N', 'Not found'), ('D', 'Downloaded'), ('U', 'Uploaded')], default='E', max_length=1),
        ),
    ]
