# Generated by Django 4.2.6 on 2024-05-06 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0005_rename_keywords_keyword_alter_affiliation_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='author_keywords',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='index_keywords',
        ),
        migrations.AddField(
            model_name='publication',
            name='keywords',
            field=models.ManyToManyField(related_name='publications', to='publication.keyword'),
        ),
    ]
