# Generated by Django 4.2.6 on 2024-05-06 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0006_remove_publication_author_keywords_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Event',
            new_name='Venue',
        ),
        migrations.RenameField(
            model_name='publication',
            old_name='event',
            new_name='venue',
        ),
    ]
