# Generated by Django 4.2.6 on 2024-05-06 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0007_rename_event_venue_rename_event_publication_venue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fulltext',
            name='type',
            field=models.CharField(choices=[('A', 'text/plain'), ('B', 'video/webm'), ('C', 'text/css'), ('D', 'audio/wav'), ('E', 'audio/mpeg'), ('I', 'audio/aac'), ('J', 'image/jpeg'), ('H', 'text/html'), ('G', 'image/gif'), ('L', 'text/xml'), ('O', 'audio/ogg'), ('N', 'image/png'), ('M', 'application/msword'), ('P', 'application/pdf'), ('Q', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'), ('R', 'application/javascript'), ('S', 'image/svg'), ('T', 'application/x-tar'), ('U', 'application/octet-stream'), ('V', 'text/csv'), ('W', 'image/webp'), ('Y', 'video/ogg'), ('X', 'application/xml'), ('Z', 'application/zip'), ('0', 'application/json'), ('1', 'application/vnd.ms-excel'), ('2', 'application/vnd.ms-powerpoint'), ('3', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'), ('4', 'video/mp4'), ('5', 'application/vnd.openxmlformats-officedocument.presentationml.presentation'), ('7', 'application/x-7z-compressed'), ('6', 'multipart/mixed'), ('8', 'multipart/alternative'), ('9', 'multipart/related')], default='T', max_length=1),
        ),
    ]
